### ISSUE TITLE
Not sure what is happening...

### ISSUE THREAD

**Issue by ghost** [adrianonrails/manga-downloader#1]
Only thing I have done is turn on cbz. 
![image](https://user-images.githubusercontent.com/36111968/51199491-81ac9400-18bc-11e9-931f-52fa3bb6b3a3.png)

**Comment by ghost** [comment]
It seems to be displaying an incorrect number. 
![image](https://user-images.githubusercontent.com/36111968/51199687-05668080-18bd-11e9-8109-bbf6190e4595.png)

**Comment by adreeeyan** [comment]
That's weird, there should be no folder if cbz is turned on.
I'll try to reproduce it on my side and get back to you.
